<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Title>Xbim Geometry Engine (P/Invoke Interop)</Title>
    <Description>Cross-platform P/Invoke interop layer for the Xbim Geometry Engine native library.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Xbim.Geometry.Engine.Interop</PackageId>
    <RootNamespace>Xbim.Geometry.Engine.Interop</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);NU1900;CS8600;CS8602;CS8603;CS8604;CS8618;CS8625;CS8714;CS8767</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\xbim-toolkit-icon.png" Pack="True" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xbim.Geometry.Abstractions\Xbim.Geometry.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Readme.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
